'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth, useOrganization } from '@/contexts';
import { OrganizationSwitcher } from '@/components';
import { ProjectList } from '@/components';
import { authApi } from '@/lib/api';
import { GenerateApi } from '@/lib/generate-api';
import { SaaSPromptInput } from '@/components/SaaSPromptInput';
import { AgentActivityFeed } from '@/components/AgentActivityFeed';
import { LandingPreview } from '@/components/LandingPreview';
import { SchemaViewer } from '@/components/SchemaViewer';
import { ABTestResults } from '@/components/ABTestResults';
import { SaveProjectModal } from '@/components/SaveProjectModal';
import { VisualEditor } from '@/components/VisualEditor';
import { useEventSource } from '@/hooks/useEventSource';
import type { GeneratedSaaSData } from '@/types';

const API_PREFIX = process.env.NEXT_PUBLIC_API_PREFIX || '/api';

export default function Dashboard() {
  const { user, isAuthenticated } = useAuth();
  const { currentOrganization } = useOrganization();
  const router = useRouter();
  const searchParams = useSearchParams();

  // Read blueprint params from URL
  const blueprintSlug = searchParams.get('blueprint');
  const initialPrompt = searchParams.get('prompt') || '';

  const [jobId, setJobId] = useState<string | null>(null);
  const [generatedHtml, setGeneratedHtml] = useState('');
  const [generatedSaaSData, setGeneratedSaaSData] = useState<GeneratedSaaSData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [agentEvents, setAgentEvents] = useState<any[]>([]);
  const [currentVariant, setCurrentVariant] = useState<string | null>(null);
  const [showRating, setShowRating] = useState(false);
  const [userRating, setUserRating] = useState<number | null>(null);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [activeTab, setActiveTab] = useState<'landing' | 'database'>('landing');
  const [isEditing, setIsEditing] = useState(false);
  const [chatInput, setChatInput] = useState('');
  const [isChatOpen, setIsChatOpen] = useState(false);
  const { events } = useEventSource(jobId ? `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}${API_PREFIX}/generate/stream/${jobId}` : '');

  useEffect(() => {
    // Redirect to signin if not authenticated
    if (!isAuthenticated) {
      router.push('/signin');
    }
  }, [isAuthenticated, router]);

  const handleLogout = async () => {
    try {
      await authApi.signout();
      router.push('/signin');
    } catch (err) {
      console.error('Logout error:', err);
      // Even if there's an error, we should still redirect to signin
      router.push('/signin');
    }
  };

  const handleRatingSubmit = async (rating: number) => {
    if (!jobId || !currentVariant) return;

    try {
      await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}${API_PREFIX}/generate/rate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          jobId,
          rating,
          variant: currentVariant
        }),
      });

      setUserRating(rating);
      setShowRating(false);
    } catch (error) {
      console.error('Error submitting rating:', error);
    }
  };

  const handleSaveProject = () => {
    if (generatedHtml && currentOrganization) {
      setShowSaveModal(true);
    }
  };

  const handleSaveProjectConfirm = async (name: string, description: string) => {
    if (!currentOrganization) return;

    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}${API_PREFIX}/organizations/${currentOrganization.id}/projects`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            name,
            description,
            idea: generatedSaaSData?.idea || initialPrompt || '', // Use idea from data or prompt input
            market: generatedSaaSData?.market || '',
            coreFeatures: generatedSaaSData?.features?.join(', ') || '', // Convert array to string
            techStack: '', // Not yet generated by LLM
            mvpPlan: generatedSaaSData?.mvpFeatures?.join(', ') || '', // Convert array to string
            gtmPlan: '', // Not yet generated by LLM
            generatedHtml,
            saasData: generatedSaaSData,
          }),
        }
      );

      const result = await response.json();

      if (result.success) {
        // Add success event to display in feed
        setAgentEvents(prev => [...prev, {
          type: 'project_saved',
          message: 'Project saved successfully',
          timestamp: new Date(),
          data: { projectId: result.project.id }
        }]);

        // Close modal
        setShowSaveModal(false);

        // Refresh projects list
        window.dispatchEvent(new CustomEvent('refreshProjects'));
      } else {
        throw new Error(result.message || 'Failed to save project');
      }
    } catch (error: any) {
      console.error('Save project error:', error);
      // Add error event to display in feed
      setAgentEvents(prev => [...prev, {
        type: 'save_error',
        message: error.message || 'Failed to save project',
        timestamp: new Date()
      }]);
    }
  };

  const handleVisualEditorUpdate = (newHtml: string) => {
    setGeneratedHtml(newHtml);
  };

  const handleToggleEditMode = () => {
    setIsEditing(!isEditing);
  };

  const handleChatSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || !generatedHtml) return;

    try {
      // Add user message to events
      setAgentEvents(prev => [...prev, {
        type: 'user_message',
        message: chatInput,
        timestamp: new Date()
      }]);

      // Clear input
      setChatInput('');

      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}${API_PREFIX}/generate/refine`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            currentHtml: generatedHtml,
            instruction: chatInput
          }),
        }
      );

      const result = await response.json();

      if (result.success) {
        // Update the HTML with the refined version
        setGeneratedHtml(result.html);

        // Add success event to display in feed
        setAgentEvents(prev => [...prev, {
          type: 'agent_completed',
          agent: 'html-refiner',
          message: 'HTML refinement complete',
          timestamp: new Date(),
          data: { html: result.html }
        }]);
      } else {
        throw new Error(result.error || 'Failed to refine HTML');
      }
    } catch (error: any) {
      console.error('Refinement error:', error);
      // Add error event to display in feed
      setAgentEvents(prev => [...prev, {
        type: 'agent_error',
        agent: 'html-refiner',
        message: error.message || 'Failed to refine HTML',
        timestamp: new Date()
      }]);
    }
  };

  const handleGenerate = async (prompt: string) => {
    setIsGenerating(true);
    setGeneratedHtml('');
    setGeneratedSaaSData(null);
    setAgentEvents([]);
    setJobId(null); // Reset jobId
    setCurrentVariant(null);
    setShowRating(false);
    setUserRating(null);
    setIsEditing(false); // Exit edit mode when generating new content

    try {
      // Step 1: Analyze the prompt
      const analyzeResult = await GenerateApi.analyzePrompt(prompt);

      if (!analyzeResult.success) {
        throw new Error(analyzeResult.error || 'Failed to analyze prompt');
      }

      // Store the SaaS data for saving later
      // Store the SaaS data for saving later
      setGeneratedSaaSData({
        ...(analyzeResult.data as GeneratedSaaSData),
        idea: prompt
      });

      // Set jobId for streaming events
      if (analyzeResult.jobId) {
        setJobId(analyzeResult.jobId);
      }

      // Add event for analysis completion
      setAgentEvents(prev => [...prev, {
        type: 'agent_completed',
        agent: 'ai-feature-builder',
        message: 'SaaS structure analysis complete',
        timestamp: new Date(),
        data: analyzeResult.data
      }]);

      // Step 2: Generate landing page
      const landingResult = await GenerateApi.generateLandingPage(analyzeResult.data as GeneratedSaaSData);

      if (!landingResult.success) {
        throw new Error(landingResult.error || 'Failed to generate landing page');
      }

      setGeneratedHtml(landingResult.html || '');

      // Set current variant if provided in the response
      if (landingResult.variant) {
        setCurrentVariant(landingResult.variant);
      }

      // Show rating option after successful generation
      setShowRating(true);
      setUserRating(null);

      // Add event for landing page completion
      setAgentEvents(prev => [...prev, {
        type: 'agent_completed',
        agent: 'landing-generator',
        message: 'Landing page generated successfully',
        timestamp: new Date(),
        data: { html: landingResult.html, variant: landingResult.variant }
      }]);

      // Add event for preview ready
      setAgentEvents(prev => [...prev, {
        type: 'preview_ready',
        message: 'Preview ready',
        timestamp: new Date(),
        data: { html: landingResult.html, variant: landingResult.variant }
      }]);
    } catch (error: any) {
      console.error('Generation error:', error);
      // Add error event to display in feed
      setAgentEvents(prev => [...prev, {
        type: 'agent_error',
        agent: 'generator',
        message: error.message || 'Failed to generate SaaS',
        timestamp: new Date()
      }]);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-gray-600">Redirecting to signin...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center">
              <h1 className="text-xl font-bold text-gray-900">
                SaaS Factory Dashboard
              </h1>
            </div>
            <div className="flex items-center space-x-4">
              <button
                onClick={handleLogout}
                className="text-red-600 hover:text-red-800 font-medium transition-colors"
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">
            Welcome back, {user?.firstName}
          </h1>
          <p className="text-gray-600 mt-2">
            {currentOrganization
              ? `Managing projects for ${currentOrganization.name}`
              : 'Select an organization to get started'}
          </p>
        </div>

        {/* Organization Info */}
        <div className="mb-8 p-6 bg-white rounded-xl shadow-md">
          <div className="flex justify-between items-center">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">Current Organization</h2>
              <p className="text-gray-600">
                {currentOrganization
                  ? `${currentOrganization.name} (${currentOrganization.plan})`
                  : 'No organization selected'}
              </p>
            </div>
            <div>
              <OrganizationSwitcher />
            </div>
          </div>
        </div>

        {/* SaaS Generator Section */}
        <div className="mb-12">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Left: Prompt Input + Agent Activity */}
            <div className="space-y-6">
              <SaaSPromptInput
                onSubmit={handleGenerate}
                initialPrompt={initialPrompt}
                isLoading={isGenerating}
              />
              <AgentActivityFeed events={[...agentEvents, ...events]} />
            </div>

            {/* Right: Live Preview */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 min-h-[600px]">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-bold text-gray-900">Project Preview</h2>

                {/* Tabs */}
                {generatedSaaSData && (
                  <div className="flex space-x-2 bg-gray-100 p-1 rounded-lg">
                    <button
                      onClick={() => setActiveTab('landing')}
                      className={`px-3 py-1.5 text-sm font-medium rounded-md transition-all ${activeTab === 'landing'
                          ? 'bg-white text-gray-900 shadow-sm'
                          : 'text-gray-500 hover:text-gray-700'
                        }`}
                    >
                      Landing Page
                    </button>
                    <button
                      onClick={() => setActiveTab('database')}
                      className={`px-3 py-1.5 text-sm font-medium rounded-md transition-all ${activeTab === 'database'
                          ? 'bg-white text-blue-600 shadow-sm'
                          : 'text-gray-500 hover:text-gray-700'
                        }`}
                    >
                      Database Schema
                    </button>
                  </div>
                )}

                <div className="flex space-x-2">
                  {generatedHtml && (
                    <button
                      onClick={handleToggleEditMode}
                      className={`px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
                        isEditing 
                          ? 'bg-green-100 text-green-800 hover:bg-green-200' 
                          : 'bg-gray-100 text-gray-800 hover:bg-gray-200'
                      }`}
                    >
                      {isEditing ? 'Exit Edit Mode' : 'Edit Mode'}
                    </button>
                  )}
                  <button
                    onClick={handleSaveProject}
                    className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-semibold hover:bg-blue-700 transition-colors"
                  >
                    Save Project
                  </button>
                </div>
              </div>

              {/* Content */}
              {activeTab === 'landing' ? (
                <>
                  {isEditing ? (
                    <div className="border rounded-lg overflow-hidden h-[500px]">
                      <VisualEditor 
                        initialHtml={generatedHtml} 
                        onUpdate={handleVisualEditorUpdate} 
                      />
                    </div>
                  ) : (
                    <LandingPreview
                      html={generatedHtml}
                      isLoading={isGenerating}
                      onSaveProject={generatedHtml ? handleSaveProject : undefined}
                    />
                  )}

                  {/* Rating Section */}
                  {showRating && !isGenerating && generatedHtml && (
                    <div className="mt-4 border-t p-4 bg-gray-50">
                      <div className="flex items-center justify-between">
                        <h3 className="font-medium text-gray-900">
                          {currentVariant ? `Template ${currentVariant}` : 'Rate this landing page'}
                        </h3>
                        {userRating ? (
                          <div className="flex items-center">
                            <span className="text-green-600 mr-2">Thank you!</span>
                            <div className="flex">
                              {[1, 2, 3, 4, 5].map((star) => (
                                <span key={star} className={`text-xl ${star <= userRating ? 'text-yellow-400' : 'text-gray-300'}`}>★</span>
                              ))}
                            </div>
                          </div>
                        ) : (
                          <div className="flex items-center space-x-1">
                            {[1, 2, 3, 4, 5].map((star) => (
                              <button
                                key={star}
                                onClick={() => handleRatingSubmit(star)}
                                className="text-gray-300 hover:text-yellow-400 focus:outline-none text-xl"
                              >
                                ★
                              </button>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </>
              ) : (
                /* Database Tab */
                <div className="space-y-4">
                  {isGenerating ? (
                    <div className="p-8 text-center">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-2"></div>
                      <p className="text-gray-500">Designing database architecture...</p>
                    </div>
                  ) : generatedSaaSData?.generatedSchema ? (
                    <SchemaViewer schema={generatedSaaSData.generatedSchema} />
                  ) : (
                    <div className="p-8 text-center text-gray-500 bg-gray-50 rounded-lg border border-dashed border-gray-300">
                      No schema generated yet. Try regenerating.
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* A/B Test Results */}
        <div className="mb-12">
          <ABTestResults />
        </div>

        {/* Existing Projects Section */}
        <ProjectList />
      </main>

      {/* Save Project Modal */}
      {showSaveModal && generatedSaaSData && (
        <SaveProjectModal
          isOpen={showSaveModal}
          onClose={() => setShowSaveModal(false)}
          projectName={generatedSaaSData.name || 'New SaaS Project'}
          projectDescription={generatedSaaSData.tagline || ''}
          generatedHtml={generatedHtml}
          saasData={generatedSaaSData}
          onSave={handleSaveProjectConfirm}
        />
      )}

      {/* Floating Chat Button */}
      {generatedHtml && (
        <button
          onClick={() => setIsChatOpen(!isChatOpen)}
          className="fixed bottom-6 right-6 bg-blue-600 text-white p-3 rounded-full shadow-lg hover:bg-blue-700 transition-all z-50"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
          </svg>
        </button>
      )}

      {/* Floating Chat Window */}
      {isChatOpen && generatedHtml && (
        <div className="fixed bottom-24 right-6 w-80 bg-white rounded-lg shadow-xl border border-gray-200 z-50">
          <div className="p-4 border-b border-gray-200">
            <div className="flex justify-between items-center">
              <h3 className="font-semibold text-gray-900">Ask AI to refine</h3>
              <button 
                onClick={() => setIsChatOpen(false)}
                className="text-gray-400 hover:text-gray-500"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                </svg>
              </button>
            </div>
          </div>
          <form onSubmit={handleChatSubmit} className="p-4">
            <div className="mb-3">
              <textarea
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="E.g., Change the background to dark, Make the buttons green..."
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                rows={3}
              />
            </div>
            <button
              type="submit"
              disabled={!chatInput.trim()}
              className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Send to AI
            </button>
          </form>
        </div>
      )}
    </div>
  );
}